/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ActivityEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'images' : IDL.Vec(ExternalBlob),
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'preferNotToSay' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'phone' : IDL.Opt(IDL.Text),
});
export const InquiryType = IDL.Variant({
  'donationQuestion' : IDL.Null,
  'other' : IDL.Null,
  'collaborationProposal' : IDL.Null,
  'feedbackSuggestion' : IDL.Null,
  'general' : IDL.Null,
  'serviceOffer' : IDL.Null,
});
export const ContactFormEntry = IDL.Record({
  'id' : IDL.Text,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'submittedBy' : IDL.Opt(IDL.Principal),
  'email' : IDL.Text,
  'replyStatus' : IDL.Variant({
    'closed' : IDL.Null,
    'notReplied' : IDL.Null,
    'pendingResponse' : IDL.Null,
    'replied' : IDL.Null,
  }),
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'adminNotes' : IDL.Opt(IDL.Text),
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Record__1 = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'paymentScreenshot' : IDL.Opt(ExternalBlob),
  'donorId' : IDL.Text,
  'description' : IDL.Text,
  'proverbId' : IDL.Opt(IDL.Nat),
  'donorGender' : Gender,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'proverbFeedback' : IDL.Opt(IDL.Bool),
});
export const PrivacyLevel = IDL.Variant({
  'publicView' : IDL.Null,
  'strictlyConfidential' : IDL.Null,
  'anonymous' : IDL.Null,
});
export const DonorProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Opt(IDL.Nat),
  'principal' : IDL.Opt(IDL.Principal),
  'displayName' : IDL.Text,
  'joinedTimestamp' : Time,
  'privacyLevel' : PrivacyLevel,
  'email' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'phone' : IDL.Text,
  'totalDonated' : IDL.Nat,
});
export const DonorPublicProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Opt(IDL.Nat),
  'principal' : IDL.Opt(IDL.Principal),
  'maskedPhone' : IDL.Text,
  'displayName' : IDL.Text,
  'joinedTimestamp' : Time,
  'email' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'totalDonated' : IDL.Nat,
});
export const Metrics = IDL.Record({
  'totalSiteViews' : IDL.Nat,
  'currentLiveViewers' : IDL.Nat,
});
export const Record = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addServiceActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'addSpendingRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmAllPendingDonations' : IDL.Func([], [], []),
  'confirmDonation' : IDL.Func([IDL.Text], [], []),
  'declineDonation' : IDL.Func([IDL.Text], [], []),
  'deleteServiceActivity' : IDL.Func([IDL.Text], [], []),
  'deleteSpendingRecord' : IDL.Func([IDL.Text], [], []),
  'getAllProverbs' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'text' : IDL.Text,
            'author' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllServiceActivities' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormEntries' : IDL.Func(
      [],
      [IDL.Vec(ContactFormEntry)],
      ['query'],
    ),
  'getDonations' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Record__1)],
      ['query'],
    ),
  'getDonorDonations' : IDL.Func([IDL.Text], [IDL.Vec(Record__1)], ['query']),
  'getDonorProfile' : IDL.Func([IDL.Text], [IDL.Opt(DonorProfile)], ['query']),
  'getDonorProfiles' : IDL.Func([], [IDL.Vec(DonorProfile)], ['query']),
  'getDonorPublicProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DonorPublicProfile)],
      ['query'],
    ),
  'getDonorPublicProfiles' : IDL.Func(
      [],
      [IDL.Vec(DonorPublicProfile)],
      ['query'],
    ),
  'getProverbsForDonation' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'text' : IDL.Text,
            'author' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getServiceActivitiesByRecentDays' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getServiceActivity' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ActivityEntry)],
      ['query'],
    ),
  'getSiteMetrics' : IDL.Func([], [Metrics], []),
  'getSpendingRecords' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Record)],
      ['query'],
    ),
  'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSpending' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrustBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'heartbeatLiveViewer' : IDL.Func([IDL.Text], [], []),
  'incrementSiteViews' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordProverbFeedback' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'registerLiveViewer' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchServiceActivitiesByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'selectProverbForDonation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType],
      [IDL.Text],
      [],
    ),
  'submitDonation' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'unregisterLiveViewer' : IDL.Func([IDL.Text], [], []),
  'updateDonorProfileAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateServiceActivity' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateSpendingRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ActivityEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'preferNotToSay' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'phone' : IDL.Opt(IDL.Text),
  });
  const InquiryType = IDL.Variant({
    'donationQuestion' : IDL.Null,
    'other' : IDL.Null,
    'collaborationProposal' : IDL.Null,
    'feedbackSuggestion' : IDL.Null,
    'general' : IDL.Null,
    'serviceOffer' : IDL.Null,
  });
  const ContactFormEntry = IDL.Record({
    'id' : IDL.Text,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'submittedBy' : IDL.Opt(IDL.Principal),
    'email' : IDL.Text,
    'replyStatus' : IDL.Variant({
      'closed' : IDL.Null,
      'notReplied' : IDL.Null,
      'pendingResponse' : IDL.Null,
      'replied' : IDL.Null,
    }),
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Record__1 = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'paymentScreenshot' : IDL.Opt(ExternalBlob),
    'donorId' : IDL.Text,
    'description' : IDL.Text,
    'proverbId' : IDL.Opt(IDL.Nat),
    'donorGender' : Gender,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'proverbFeedback' : IDL.Opt(IDL.Bool),
  });
  const PrivacyLevel = IDL.Variant({
    'publicView' : IDL.Null,
    'strictlyConfidential' : IDL.Null,
    'anonymous' : IDL.Null,
  });
  const DonorProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Opt(IDL.Nat),
    'principal' : IDL.Opt(IDL.Principal),
    'displayName' : IDL.Text,
    'joinedTimestamp' : Time,
    'privacyLevel' : PrivacyLevel,
    'email' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'phone' : IDL.Text,
    'totalDonated' : IDL.Nat,
  });
  const DonorPublicProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Opt(IDL.Nat),
    'principal' : IDL.Opt(IDL.Principal),
    'maskedPhone' : IDL.Text,
    'displayName' : IDL.Text,
    'joinedTimestamp' : Time,
    'email' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'totalDonated' : IDL.Nat,
  });
  const Metrics = IDL.Record({
    'totalSiteViews' : IDL.Nat,
    'currentLiveViewers' : IDL.Nat,
  });
  const Record = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addServiceActivity' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'addSpendingRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmAllPendingDonations' : IDL.Func([], [], []),
    'confirmDonation' : IDL.Func([IDL.Text], [], []),
    'declineDonation' : IDL.Func([IDL.Text], [], []),
    'deleteServiceActivity' : IDL.Func([IDL.Text], [], []),
    'deleteSpendingRecord' : IDL.Func([IDL.Text], [], []),
    'getAllProverbs' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'text' : IDL.Text,
              'author' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllServiceActivities' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormEntries' : IDL.Func(
        [],
        [IDL.Vec(ContactFormEntry)],
        ['query'],
      ),
    'getDonations' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Record__1)],
        ['query'],
      ),
    'getDonorDonations' : IDL.Func([IDL.Text], [IDL.Vec(Record__1)], ['query']),
    'getDonorProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DonorProfile)],
        ['query'],
      ),
    'getDonorProfiles' : IDL.Func([], [IDL.Vec(DonorProfile)], ['query']),
    'getDonorPublicProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DonorPublicProfile)],
        ['query'],
      ),
    'getDonorPublicProfiles' : IDL.Func(
        [],
        [IDL.Vec(DonorPublicProfile)],
        ['query'],
      ),
    'getProverbsForDonation' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'text' : IDL.Text,
              'author' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getServiceActivitiesByRecentDays' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getServiceActivity' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ActivityEntry)],
        ['query'],
      ),
    'getSiteMetrics' : IDL.Func([], [Metrics], []),
    'getSpendingRecords' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Record)],
        ['query'],
      ),
    'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSpending' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrustBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'heartbeatLiveViewer' : IDL.Func([IDL.Text], [], []),
    'incrementSiteViews' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordProverbFeedback' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'registerLiveViewer' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchServiceActivitiesByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'selectProverbForDonation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType],
        [IDL.Text],
        [],
      ),
    'submitDonation' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'unregisterLiveViewer' : IDL.Func([IDL.Text], [], []),
    'updateDonorProfileAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateServiceActivity' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateSpendingRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };