/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DonationInput {
  'utr' : string,
  'displayName' : string,
  'donorId' : string,
  'description' : string,
  'email' : [] | [string],
  'phone' : string,
  'amount' : bigint,
}
export interface DonorProfile {
  'id' : string,
  'principal' : [] | [Principal],
  'displayName' : string,
  'joinedTimestamp' : Time,
  'email' : [] | [string],
  'phone' : string,
  'totalDonated' : bigint,
}
export interface DonorPublicProfile {
  'id' : string,
  'principal' : [] | [Principal],
  'maskedPhone' : string,
  'displayName' : string,
  'joinedTimestamp' : Time,
  'email' : [] | [string],
  'totalDonated' : bigint,
}
export interface Metrics {
  'totalSiteViews' : bigint,
  'currentLiveViewers' : bigint,
}
export interface Record {
  'id' : string,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface Record__1 {
  'id' : string,
  'utr' : string,
  'status' : Status,
  'donorId' : string,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export type Status = { 'pending' : null } |
  { 'confirmed' : null } |
  { 'failed' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonation' : ActorMethod<[DonationInput], string>,
  'addSpendingRecord' : ActorMethod<[bigint, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmAllPendingDonations' : ActorMethod<[], undefined>,
  'confirmDonation' : ActorMethod<[string], undefined>,
  'declineDonation' : ActorMethod<[string], undefined>,
  'deleteSpendingRecord' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonations' : ActorMethod<[bigint, bigint], Array<Record__1>>,
  'getDonorDonations' : ActorMethod<[string], Array<Record__1>>,
  'getDonorProfile' : ActorMethod<[string], [] | [DonorProfile]>,
  'getDonorProfiles' : ActorMethod<[], Array<DonorProfile>>,
  'getDonorPublicProfile' : ActorMethod<[string], [] | [DonorPublicProfile]>,
  'getDonorPublicProfiles' : ActorMethod<[], Array<DonorPublicProfile>>,
  'getSiteMetrics' : ActorMethod<[], Metrics>,
  'getSpendingRecords' : ActorMethod<[bigint, bigint], Array<Record>>,
  'getTotalDonations' : ActorMethod<[], bigint>,
  'getTotalSpending' : ActorMethod<[], bigint>,
  'getTrustBalance' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'heartbeatLiveViewer' : ActorMethod<[string], undefined>,
  'incrementSiteViews' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerLiveViewer' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unregisterLiveViewer' : ActorMethod<[string], undefined>,
  'updateDonorProfileAdmin' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'updateSpendingRecord' : ActorMethod<[string, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];