/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DonationInput = IDL.Record({
  'utr' : IDL.Text,
  'displayName' : IDL.Text,
  'donorId' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const NotificationPriority = IDL.Variant({
  'low' : IDL.Null,
  'normal' : IDL.Null,
  'high' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
  'priority' : NotificationPriority,
  'isNew' : IDL.Bool,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'preferNotToSay' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'phone' : IDL.Opt(IDL.Text),
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Record__1 = IDL.Record({
  'id' : IDL.Text,
  'utr' : IDL.Text,
  'status' : Status,
  'donorId' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const DonorProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Opt(IDL.Nat),
  'principal' : IDL.Opt(IDL.Principal),
  'displayName' : IDL.Text,
  'joinedTimestamp' : Time,
  'email' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'phone' : IDL.Text,
  'totalDonated' : IDL.Nat,
});
export const DonorPublicProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Opt(IDL.Nat),
  'principal' : IDL.Opt(IDL.Principal),
  'maskedPhone' : IDL.Text,
  'displayName' : IDL.Text,
  'joinedTimestamp' : Time,
  'email' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'totalDonated' : IDL.Nat,
});
export const Metrics = IDL.Record({
  'totalSiteViews' : IDL.Nat,
  'currentLiveViewers' : IDL.Nat,
});
export const Record = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeNotification' : IDL.Func([IDL.Nat], [], []),
  'addDonation' : IDL.Func([DonationInput], [IDL.Text], []),
  'addSpendingRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmAllPendingDonations' : IDL.Func([], [], []),
  'confirmDonation' : IDL.Func([IDL.Text], [], []),
  'declineDonation' : IDL.Func([IDL.Text], [], []),
  'deleteSpendingRecord' : IDL.Func([IDL.Text], [], []),
  'getAdminNotifications' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonations' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Record__1)],
      ['query'],
    ),
  'getDonorDonations' : IDL.Func([IDL.Text], [IDL.Vec(Record__1)], ['query']),
  'getDonorProfile' : IDL.Func([IDL.Text], [IDL.Opt(DonorProfile)], ['query']),
  'getDonorProfiles' : IDL.Func([], [IDL.Vec(DonorProfile)], ['query']),
  'getDonorPublicProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DonorPublicProfile)],
      ['query'],
    ),
  'getDonorPublicProfiles' : IDL.Func(
      [],
      [IDL.Vec(DonorPublicProfile)],
      ['query'],
    ),
  'getSiteMetrics' : IDL.Func([], [Metrics], ['query']),
  'getSpendingRecords' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Record)],
      ['query'],
    ),
  'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSpending' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrustBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'heartbeatLiveViewer' : IDL.Func([IDL.Text], [], []),
  'incrementSiteViews' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'registerLiveViewer' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unregisterLiveViewer' : IDL.Func([IDL.Text], [], []),
  'updateDonorProfileAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateSpendingRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DonationInput = IDL.Record({
    'utr' : IDL.Text,
    'displayName' : IDL.Text,
    'donorId' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const NotificationPriority = IDL.Variant({
    'low' : IDL.Null,
    'normal' : IDL.Null,
    'high' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
    'priority' : NotificationPriority,
    'isNew' : IDL.Bool,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'preferNotToSay' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Record__1 = IDL.Record({
    'id' : IDL.Text,
    'utr' : IDL.Text,
    'status' : Status,
    'donorId' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const DonorProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Opt(IDL.Nat),
    'principal' : IDL.Opt(IDL.Principal),
    'displayName' : IDL.Text,
    'joinedTimestamp' : Time,
    'email' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'phone' : IDL.Text,
    'totalDonated' : IDL.Nat,
  });
  const DonorPublicProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Opt(IDL.Nat),
    'principal' : IDL.Opt(IDL.Principal),
    'maskedPhone' : IDL.Text,
    'displayName' : IDL.Text,
    'joinedTimestamp' : Time,
    'email' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'totalDonated' : IDL.Nat,
  });
  const Metrics = IDL.Record({
    'totalSiteViews' : IDL.Nat,
    'currentLiveViewers' : IDL.Nat,
  });
  const Record = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeNotification' : IDL.Func([IDL.Nat], [], []),
    'addDonation' : IDL.Func([DonationInput], [IDL.Text], []),
    'addSpendingRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmAllPendingDonations' : IDL.Func([], [], []),
    'confirmDonation' : IDL.Func([IDL.Text], [], []),
    'declineDonation' : IDL.Func([IDL.Text], [], []),
    'deleteSpendingRecord' : IDL.Func([IDL.Text], [], []),
    'getAdminNotifications' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonations' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Record__1)],
        ['query'],
      ),
    'getDonorDonations' : IDL.Func([IDL.Text], [IDL.Vec(Record__1)], ['query']),
    'getDonorProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DonorProfile)],
        ['query'],
      ),
    'getDonorProfiles' : IDL.Func([], [IDL.Vec(DonorProfile)], ['query']),
    'getDonorPublicProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DonorPublicProfile)],
        ['query'],
      ),
    'getDonorPublicProfiles' : IDL.Func(
        [],
        [IDL.Vec(DonorPublicProfile)],
        ['query'],
      ),
    'getSiteMetrics' : IDL.Func([], [Metrics], ['query']),
    'getSpendingRecords' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Record)],
        ['query'],
      ),
    'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSpending' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrustBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'heartbeatLiveViewer' : IDL.Func([IDL.Text], [], []),
    'incrementSiteViews' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'registerLiveViewer' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unregisterLiveViewer' : IDL.Func([IDL.Text], [], []),
    'updateDonorProfileAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateSpendingRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };