/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DonationInput = IDL.Record({
  'displayName' : IDL.Text,
  'donorId' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const Record__1 = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'donorId' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const Profile = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Opt(IDL.Principal),
  'displayName' : IDL.Text,
  'joinedTimestamp' : Time,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'totalDonated' : IDL.Nat,
});
export const Record = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonation' : IDL.Func([DonationInput], [IDL.Text], []),
  'addSpendingRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmDonation' : IDL.Func([IDL.Text], [], []),
  'declineDonation' : IDL.Func([IDL.Text], [], []),
  'deleteSpendingRecord' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonations' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Record__1)],
      ['query'],
    ),
  'getDonorDonations' : IDL.Func([IDL.Text], [IDL.Vec(Record__1)], ['query']),
  'getDonorProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'getDonorProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getSpendingRecords' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Record)],
      ['query'],
    ),
  'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSpending' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrustBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDonorProfileAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSpendingRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DonationInput = IDL.Record({
    'displayName' : IDL.Text,
    'donorId' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Record__1 = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'donorId' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Opt(IDL.Principal),
    'displayName' : IDL.Text,
    'joinedTimestamp' : Time,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'totalDonated' : IDL.Nat,
  });
  const Record = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonation' : IDL.Func([DonationInput], [IDL.Text], []),
    'addSpendingRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmDonation' : IDL.Func([IDL.Text], [], []),
    'declineDonation' : IDL.Func([IDL.Text], [], []),
    'deleteSpendingRecord' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonations' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Record__1)],
        ['query'],
      ),
    'getDonorDonations' : IDL.Func([IDL.Text], [IDL.Vec(Record__1)], ['query']),
    'getDonorProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
    'getDonorProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getSpendingRecords' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Record)],
        ['query'],
      ),
    'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSpending' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrustBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDonorProfileAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSpendingRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };