/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'id' : string,
  'title' : string,
  'description' : string,
  'author' : string,
  'notes' : [] | [string],
  'timestamp' : Time,
  'images' : Array<ExternalBlob>,
}
export interface ContactFormEntry {
  'id' : string,
  'inquiryType' : InquiryType,
  'name' : string,
  'submittedBy' : [] | [Principal],
  'email' : string,
  'replyStatus' : { 'closed' : null } |
    { 'notReplied' : null } |
    { 'pendingResponse' : null } |
    { 'replied' : null },
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'adminNotes' : [] | [string],
}
export interface DonorProfile {
  'id' : string,
  'age' : [] | [bigint],
  'principal' : [] | [Principal],
  'displayName' : string,
  'joinedTimestamp' : Time,
  'privacyLevel' : PrivacyLevel,
  'email' : [] | [string],
  'gender' : Gender,
  'phone' : string,
  'totalDonated' : bigint,
}
export interface DonorPublicProfile {
  'id' : string,
  'age' : [] | [bigint],
  'principal' : [] | [Principal],
  'maskedPhone' : string,
  'displayName' : string,
  'joinedTimestamp' : Time,
  'email' : [] | [string],
  'gender' : Gender,
  'totalDonated' : bigint,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null } |
  { 'preferNotToSay' : null };
export type InquiryType = { 'donationQuestion' : null } |
  { 'other' : null } |
  { 'collaborationProposal' : null } |
  { 'feedbackSuggestion' : null } |
  { 'general' : null } |
  { 'serviceOffer' : null };
export interface Metrics {
  'totalSiteViews' : bigint,
  'currentLiveViewers' : bigint,
}
export type PrivacyLevel = { 'publicView' : null } |
  { 'strictlyConfidential' : null } |
  { 'anonymous' : null };
export interface Record {
  'id' : string,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface Record__1 {
  'id' : string,
  'status' : Status,
  'paymentScreenshot' : [] | [ExternalBlob],
  'donorId' : string,
  'description' : string,
  'proverbId' : [] | [bigint],
  'donorGender' : Gender,
  'timestamp' : Time,
  'amount' : bigint,
  'proverbFeedback' : [] | [boolean],
}
export type Status = { 'pending' : null } |
  { 'confirmed' : null } |
  { 'failed' : null };
export type Time = bigint;
export interface UserProfile {
  'age' : [] | [bigint],
  'name' : string,
  'email' : [] | [string],
  'gender' : Gender,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addServiceActivity' : ActorMethod<
    [string, string, Array<ExternalBlob>, string, [] | [string]],
    string
  >,
  'addSpendingRecord' : ActorMethod<[bigint, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmAllPendingDonations' : ActorMethod<[], undefined>,
  'confirmDonation' : ActorMethod<[string], undefined>,
  'declineDonation' : ActorMethod<[string], undefined>,
  'deleteServiceActivity' : ActorMethod<[string], undefined>,
  'deleteSpendingRecord' : ActorMethod<[string], undefined>,
  'getAllProverbs' : ActorMethod<
    [],
    Array<{ 'id' : string, 'text' : string, 'author' : string }>
  >,
  'getAllServiceActivities' : ActorMethod<
    [bigint, bigint],
    Array<ActivityEntry>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactFormEntries' : ActorMethod<[], Array<ContactFormEntry>>,
  'getDonations' : ActorMethod<[bigint, bigint], Array<Record__1>>,
  'getDonorDonations' : ActorMethod<[string], Array<Record__1>>,
  'getDonorProfile' : ActorMethod<[string], [] | [DonorProfile]>,
  'getDonorProfiles' : ActorMethod<[], Array<DonorProfile>>,
  'getDonorPublicProfile' : ActorMethod<[string], [] | [DonorPublicProfile]>,
  'getDonorPublicProfiles' : ActorMethod<[], Array<DonorPublicProfile>>,
  'getProverbsForDonation' : ActorMethod<
    [string],
    Array<{ 'id' : string, 'text' : string, 'author' : string }>
  >,
  'getServiceActivitiesByRecentDays' : ActorMethod<
    [bigint],
    Array<ActivityEntry>
  >,
  'getServiceActivity' : ActorMethod<[string], [] | [ActivityEntry]>,
  'getSiteMetrics' : ActorMethod<[], Metrics>,
  'getSpendingRecords' : ActorMethod<[bigint, bigint], Array<Record>>,
  'getTotalDonations' : ActorMethod<[], bigint>,
  'getTotalSpending' : ActorMethod<[], bigint>,
  'getTrustBalance' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'heartbeatLiveViewer' : ActorMethod<[string], undefined>,
  'incrementSiteViews' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordProverbFeedback' : ActorMethod<[string, boolean], undefined>,
  'registerLiveViewer' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchServiceActivitiesByTitle' : ActorMethod<
    [string],
    Array<ActivityEntry>
  >,
  'selectProverbForDonation' : ActorMethod<[string, bigint], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, InquiryType],
    string
  >,
  'submitDonation' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      [] | [string],
      string,
      [] | [ExternalBlob],
    ],
    string
  >,
  'unregisterLiveViewer' : ActorMethod<[string], undefined>,
  'updateDonorProfileAdmin' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'updateServiceActivity' : ActorMethod<
    [string, string, string, Array<ExternalBlob>, string, [] | [string]],
    undefined
  >,
  'updateSpendingRecord' : ActorMethod<[string, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];