/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ContactFormEntry {
    id: string;
    inquiryType: InquiryType;
    name: string;
    submittedBy?: Principal;
    email: string;
    replyStatus: Variant_closed_notReplied_pendingResponse_replied;
    message: string;
    timestamp: Time;
    phone: string;
    adminNotes?: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DonorPublicProfile {
    id: string;
    age?: bigint;
    principal?: Principal;
    maskedPhone: string;
    displayName: string;
    joinedTimestamp: Time;
    email?: string;
    gender: Gender;
    totalDonated: bigint;
}
export interface Record_ {
    id: string;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface Record__1 {
    id: string;
    status: Status;
    paymentScreenshot?: ExternalBlob;
    donorId: string;
    description: string;
    proverbId?: bigint;
    donorGender: Gender;
    timestamp: Time;
    amount: bigint;
    proverbFeedback?: boolean;
}
export interface DonorProfile {
    id: string;
    age?: bigint;
    principal?: Principal;
    displayName: string;
    joinedTimestamp: Time;
    privacyLevel: PrivacyLevel;
    email?: string;
    gender: Gender;
    phone: string;
    totalDonated: bigint;
}
export interface ActivityEntry {
    id: string;
    title: string;
    description: string;
    author: string;
    notes?: string;
    timestamp: Time;
    images: Array<ExternalBlob>;
}
export interface UserProfile {
    age?: bigint;
    name: string;
    email?: string;
    gender: Gender;
    phone?: string;
}
export interface Metrics {
    totalSiteViews: bigint;
    currentLiveViewers: bigint;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male",
    preferNotToSay = "preferNotToSay"
}
export enum InquiryType {
    donationQuestion = "donationQuestion",
    other = "other",
    collaborationProposal = "collaborationProposal",
    feedbackSuggestion = "feedbackSuggestion",
    general = "general",
    serviceOffer = "serviceOffer"
}
export enum PrivacyLevel {
    publicView = "publicView",
    strictlyConfidential = "strictlyConfidential",
    anonymous = "anonymous"
}
export enum Status {
    pending = "pending",
    confirmed = "confirmed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_closed_notReplied_pendingResponse_replied {
    closed = "closed",
    notReplied = "notReplied",
    pendingResponse = "pendingResponse",
    replied = "replied"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addServiceActivity(title: string, description: string, images: Array<ExternalBlob>, author: string, notes: string | null): Promise<string>;
    addSpendingRecord(amount: bigint, description: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmAllPendingDonations(): Promise<void>;
    confirmDonation(donationId: string): Promise<void>;
    declineDonation(donationId: string): Promise<void>;
    deleteServiceActivity(id: string): Promise<void>;
    deleteSpendingRecord(id: string): Promise<void>;
    getAllProverbs(): Promise<Array<{
        id: string;
        text: string;
        author: string;
    }>>;
    getAllServiceActivities(limit: bigint, offset: bigint): Promise<Array<ActivityEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactFormEntries(): Promise<Array<ContactFormEntry>>;
    getDonations(limit: bigint, offset: bigint): Promise<Array<Record__1>>;
    getDonorDonations(donorId: string): Promise<Array<Record__1>>;
    getDonorProfile(donorId: string): Promise<DonorProfile | null>;
    getDonorProfiles(): Promise<Array<DonorProfile>>;
    getDonorPublicProfile(donorId: string): Promise<DonorPublicProfile | null>;
    getDonorPublicProfiles(): Promise<Array<DonorPublicProfile>>;
    getProverbsForDonation(donationId: string): Promise<Array<{
        id: string;
        text: string;
        author: string;
    }>>;
    getServiceActivitiesByRecentDays(days: bigint): Promise<Array<ActivityEntry>>;
    getServiceActivity(id: string): Promise<ActivityEntry | null>;
    getSiteMetrics(): Promise<Metrics>;
    getSpendingRecords(limit: bigint, offset: bigint): Promise<Array<Record_>>;
    getTotalDonations(): Promise<bigint>;
    getTotalSpending(): Promise<bigint>;
    getTrustBalance(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    heartbeatLiveViewer(sessionId: string): Promise<void>;
    incrementSiteViews(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordProverbFeedback(donationId: string, isLiked: boolean): Promise<void>;
    registerLiveViewer(sessionId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchServiceActivitiesByTitle(keyword: string): Promise<Array<ActivityEntry>>;
    selectProverbForDonation(donationId: string, proverbId: bigint): Promise<void>;
    submitContactForm(name: string, email: string, phone: string, message: string, inquiryType: InquiryType): Promise<string>;
    submitDonation(donorId: string, amount: bigint, description: string, displayName: string, email: string | null, phone: string, paymentScreenshot: ExternalBlob | null): Promise<string>;
    unregisterLiveViewer(sessionId: string): Promise<void>;
    updateDonorProfileAdmin(donorId: string, displayName: string, email: string | null, phone: string): Promise<void>;
    updateServiceActivity(id: string, title: string, description: string, images: Array<ExternalBlob>, author: string, notes: string | null): Promise<void>;
    updateSpendingRecord(id: string, amount: bigint, description: string): Promise<void>;
}
import type { ActivityEntry as _ActivityEntry, ContactFormEntry as _ContactFormEntry, DonorProfile as _DonorProfile, DonorPublicProfile as _DonorPublicProfile, ExternalBlob as _ExternalBlob, Gender as _Gender, InquiryType as _InquiryType, PrivacyLevel as _PrivacyLevel, Record__1 as _Record__1, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addServiceActivity(arg0: string, arg1: string, arg2: Array<ExternalBlob>, arg3: string, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceActivity(arg0, arg1, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceActivity(arg0, arg1, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addSpendingRecord(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSpendingRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSpendingRecord(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmAllPendingDonations(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmAllPendingDonations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmAllPendingDonations();
            return result;
        }
    }
    async confirmDonation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmDonation(arg0);
            return result;
        }
    }
    async declineDonation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineDonation(arg0);
            return result;
        }
    }
    async deleteServiceActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServiceActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServiceActivity(arg0);
            return result;
        }
    }
    async deleteSpendingRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSpendingRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSpendingRecord(arg0);
            return result;
        }
    }
    async getAllProverbs(): Promise<Array<{
        id: string;
        text: string;
        author: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProverbs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProverbs();
            return result;
        }
    }
    async getAllServiceActivities(arg0: bigint, arg1: bigint): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceActivities(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceActivities(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactFormEntries(): Promise<Array<ContactFormEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactFormEntries();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactFormEntries();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonations(arg0: bigint, arg1: bigint): Promise<Array<Record__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonations(arg0, arg1);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonations(arg0, arg1);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorDonations(arg0: string): Promise<Array<Record__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorDonations(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorDonations(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorProfile(arg0: string): Promise<DonorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorProfiles(): Promise<Array<DonorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorProfiles();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorProfiles();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorPublicProfile(arg0: string): Promise<DonorPublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorPublicProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorPublicProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorPublicProfiles(): Promise<Array<DonorPublicProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorPublicProfiles();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorPublicProfiles();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProverbsForDonation(arg0: string): Promise<Array<{
        id: string;
        text: string;
        author: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProverbsForDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProverbsForDonation(arg0);
            return result;
        }
    }
    async getServiceActivitiesByRecentDays(arg0: bigint): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceActivitiesByRecentDays(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceActivitiesByRecentDays(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceActivity(arg0: string): Promise<ActivityEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceActivity(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceActivity(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteMetrics(): Promise<Metrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteMetrics();
            return result;
        }
    }
    async getSpendingRecords(arg0: bigint, arg1: bigint): Promise<Array<Record_>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingRecords(arg0, arg1);
            return result;
        }
    }
    async getTotalDonations(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalDonations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalDonations();
            return result;
        }
    }
    async getTotalSpending(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSpending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSpending();
            return result;
        }
    }
    async getTrustBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrustBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrustBalance();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async heartbeatLiveViewer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.heartbeatLiveViewer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.heartbeatLiveViewer(arg0);
            return result;
        }
    }
    async incrementSiteViews(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementSiteViews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementSiteViews();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordProverbFeedback(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordProverbFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordProverbFeedback(arg0, arg1);
            return result;
        }
    }
    async registerLiveViewer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerLiveViewer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerLiveViewer(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchServiceActivitiesByTitle(arg0: string): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchServiceActivitiesByTitle(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchServiceActivitiesByTitle(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async selectProverbForDonation(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectProverbForDonation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectProverbForDonation(arg0, arg1);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: InquiryType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, to_candid_InquiryType_n54(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, to_candid_InquiryType_n54(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitDonation(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string | null, arg5: string, arg6: ExternalBlob | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDonation(arg0, arg1, arg2, arg3, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), arg5, await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDonation(arg0, arg1, arg2, arg3, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), arg5, await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async unregisterLiveViewer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unregisterLiveViewer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unregisterLiveViewer(arg0);
            return result;
        }
    }
    async updateDonorProfileAdmin(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonorProfileAdmin(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonorProfileAdmin(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateServiceActivity(arg0: string, arg1: string, arg2: string, arg3: Array<ExternalBlob>, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceActivity(arg0, arg1, arg2, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceActivity(arg0, arg1, arg2, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateSpendingRecord(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSpendingRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSpendingRecord(arg0, arg1, arg2);
            return result;
        }
    }
}
async function from_candid_ActivityEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEntry): Promise<ActivityEntry> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ContactFormEntry_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactFormEntry): ContactFormEntry {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DonorProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorProfile): DonorProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_DonorPublicProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorPublicProfile): DonorPublicProfile {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PrivacyLevel_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrivacyLevel): PrivacyLevel {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_Record__1_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record__1): Promise<Record__1> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DonorProfile]): DonorProfile | null {
    return value.length === 0 ? null : from_candid_DonorProfile_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DonorPublicProfile]): DonorPublicProfile | null {
    return value.length === 0 ? null : from_candid_DonorPublicProfile_n46(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActivityEntry]): Promise<ActivityEntry | null> {
    return value.length === 0 ? null : await from_candid_ActivityEntry_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    author: string;
    notes: [] | [string];
    timestamp: _Time;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    description: string;
    author: string;
    notes?: string;
    timestamp: Time;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        author: value.author,
        notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        images: await from_candid_vec_n17(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    name: string;
    email: [] | [string];
    gender: _Gender;
    phone: [] | [string];
}): {
    age?: bigint;
    name: string;
    email?: string;
    gender: Gender;
    phone?: string;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.age)),
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.email)),
        gender: from_candid_Gender_n22(_uploadFile, _downloadFile, value.gender),
        phone: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inquiryType: _InquiryType;
    name: string;
    submittedBy: [] | [Principal];
    email: string;
    replyStatus: {
        closed: null;
    } | {
        notReplied: null;
    } | {
        pendingResponse: null;
    } | {
        replied: null;
    };
    message: string;
    timestamp: _Time;
    phone: string;
    adminNotes: [] | [string];
}): {
    id: string;
    inquiryType: InquiryType;
    name: string;
    submittedBy?: Principal;
    email: string;
    replyStatus: Variant_closed_notReplied_pendingResponse_replied;
    message: string;
    timestamp: Time;
    phone: string;
    adminNotes?: string;
} {
    return {
        id: value.id,
        inquiryType: from_candid_InquiryType_n29(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        submittedBy: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.submittedBy)),
        email: value.email,
        replyStatus: from_candid_variant_n32(_uploadFile, _downloadFile, value.replyStatus),
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone,
        adminNotes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.adminNotes))
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    paymentScreenshot: [] | [_ExternalBlob];
    donorId: string;
    description: string;
    proverbId: [] | [bigint];
    donorGender: _Gender;
    timestamp: _Time;
    amount: bigint;
    proverbFeedback: [] | [boolean];
}): Promise<{
    id: string;
    status: Status;
    paymentScreenshot?: ExternalBlob;
    donorId: string;
    description: string;
    proverbId?: bigint;
    donorGender: Gender;
    timestamp: Time;
    amount: bigint;
    proverbFeedback?: boolean;
}> {
    return {
        id: value.id,
        status: from_candid_Status_n36(_uploadFile, _downloadFile, value.status),
        paymentScreenshot: record_opt_to_undefined(await from_candid_opt_n38(_uploadFile, _downloadFile, value.paymentScreenshot)),
        donorId: value.donorId,
        description: value.description,
        proverbId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.proverbId)),
        donorGender: from_candid_Gender_n22(_uploadFile, _downloadFile, value.donorGender),
        timestamp: value.timestamp,
        amount: value.amount,
        proverbFeedback: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.proverbFeedback))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: [] | [bigint];
    principal: [] | [Principal];
    displayName: string;
    joinedTimestamp: _Time;
    privacyLevel: _PrivacyLevel;
    email: [] | [string];
    gender: _Gender;
    phone: string;
    totalDonated: bigint;
}): {
    id: string;
    age?: bigint;
    principal?: Principal;
    displayName: string;
    joinedTimestamp: Time;
    privacyLevel: PrivacyLevel;
    email?: string;
    gender: Gender;
    phone: string;
    totalDonated: bigint;
} {
    return {
        id: value.id,
        age: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.age)),
        principal: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.principal)),
        displayName: value.displayName,
        joinedTimestamp: value.joinedTimestamp,
        privacyLevel: from_candid_PrivacyLevel_n42(_uploadFile, _downloadFile, value.privacyLevel),
        email: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.email)),
        gender: from_candid_Gender_n22(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        totalDonated: value.totalDonated
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: [] | [bigint];
    principal: [] | [Principal];
    maskedPhone: string;
    displayName: string;
    joinedTimestamp: _Time;
    email: [] | [string];
    gender: _Gender;
    totalDonated: bigint;
}): {
    id: string;
    age?: bigint;
    principal?: Principal;
    maskedPhone: string;
    displayName: string;
    joinedTimestamp: Time;
    email?: string;
    gender: Gender;
    totalDonated: bigint;
} {
    return {
        id: value.id,
        age: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.age)),
        principal: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.principal)),
        maskedPhone: value.maskedPhone,
        displayName: value.displayName,
        joinedTimestamp: value.joinedTimestamp,
        email: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.email)),
        gender: from_candid_Gender_n22(_uploadFile, _downloadFile, value.gender),
        totalDonated: value.totalDonated
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    preferNotToSay: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : "preferNotToSay" in value ? Gender.preferNotToSay : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    donationQuestion: null;
} | {
    other: null;
} | {
    collaborationProposal: null;
} | {
    feedbackSuggestion: null;
} | {
    general: null;
} | {
    serviceOffer: null;
}): InquiryType {
    return "donationQuestion" in value ? InquiryType.donationQuestion : "other" in value ? InquiryType.other : "collaborationProposal" in value ? InquiryType.collaborationProposal : "feedbackSuggestion" in value ? InquiryType.feedbackSuggestion : "general" in value ? InquiryType.general : "serviceOffer" in value ? InquiryType.serviceOffer : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    notReplied: null;
} | {
    pendingResponse: null;
} | {
    replied: null;
}): Variant_closed_notReplied_pendingResponse_replied {
    return "closed" in value ? Variant_closed_notReplied_pendingResponse_replied.closed : "notReplied" in value ? Variant_closed_notReplied_pendingResponse_replied.notReplied : "pendingResponse" in value ? Variant_closed_notReplied_pendingResponse_replied.pendingResponse : "replied" in value ? Variant_closed_notReplied_pendingResponse_replied.replied : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
} | {
    failed: null;
}): Status {
    return "pending" in value ? Status.pending : "confirmed" in value ? Status.confirmed : "failed" in value ? Status.failed : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicView: null;
} | {
    strictlyConfidential: null;
} | {
    anonymous: null;
}): PrivacyLevel {
    return "publicView" in value ? PrivacyLevel.publicView : "strictlyConfidential" in value ? PrivacyLevel.strictlyConfidential : "anonymous" in value ? PrivacyLevel.anonymous : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEntry>): Promise<Array<ActivityEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ActivityEntry_n14(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactFormEntry>): Array<ContactFormEntry> {
    return value.map((x)=>from_candid_ContactFormEntry_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record__1>): Promise<Array<Record__1>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Record__1_n34(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorProfile>): Array<DonorProfile> {
    return value.map((x)=>from_candid_DonorProfile_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorPublicProfile>): Array<DonorPublicProfile> {
    return value.map((x)=>from_candid_DonorPublicProfile_n46(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryType_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    name: string;
    email?: string;
    gender: Gender;
    phone?: string;
}): {
    age: [] | [bigint];
    name: string;
    email: [] | [string];
    gender: _Gender;
    phone: [] | [string];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        gender: to_candid_Gender_n52(_uploadFile, _downloadFile, value.gender),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    preferNotToSay: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value == Gender.preferNotToSay ? {
        preferNotToSay: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    donationQuestion: null;
} | {
    other: null;
} | {
    collaborationProposal: null;
} | {
    feedbackSuggestion: null;
} | {
    general: null;
} | {
    serviceOffer: null;
} {
    return value == InquiryType.donationQuestion ? {
        donationQuestion: null
    } : value == InquiryType.other ? {
        other: null
    } : value == InquiryType.collaborationProposal ? {
        collaborationProposal: null
    } : value == InquiryType.feedbackSuggestion ? {
        feedbackSuggestion: null
    } : value == InquiryType.general ? {
        general: null
    } : value == InquiryType.serviceOffer ? {
        serviceOffer: null
    } : value;
}
async function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
