/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DonationInput {
    utr: string;
    displayName: string;
    donorId: string;
    description: string;
    email?: string;
    phone: string;
    amount: bigint;
}
export type Time = bigint;
export interface DonorPublicProfile {
    id: string;
    principal?: Principal;
    maskedPhone: string;
    displayName: string;
    joinedTimestamp: Time;
    email?: string;
    totalDonated: bigint;
}
export interface Record_ {
    id: string;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface Record__1 {
    id: string;
    utr: string;
    status: Status;
    donorId: string;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface DonorProfile {
    id: string;
    principal?: Principal;
    displayName: string;
    joinedTimestamp: Time;
    email?: string;
    phone: string;
    totalDonated: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    phone?: string;
}
export interface Metrics {
    totalSiteViews: bigint;
    currentLiveViewers: bigint;
}
export enum Status {
    pending = "pending",
    confirmed = "confirmed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDonation(donationInput: DonationInput): Promise<string>;
    addSpendingRecord(amount: bigint, description: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmAllPendingDonations(): Promise<void>;
    confirmDonation(donationId: string): Promise<void>;
    declineDonation(donationId: string): Promise<void>;
    deleteSpendingRecord(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonations(limit: bigint, offset: bigint): Promise<Array<Record__1>>;
    getDonorDonations(donorId: string): Promise<Array<Record__1>>;
    getDonorProfile(donorId: string): Promise<DonorProfile | null>;
    getDonorProfiles(): Promise<Array<DonorProfile>>;
    getDonorPublicProfile(donorId: string): Promise<DonorPublicProfile | null>;
    getDonorPublicProfiles(): Promise<Array<DonorPublicProfile>>;
    getSiteMetrics(): Promise<Metrics>;
    getSpendingRecords(limit: bigint, offset: bigint): Promise<Array<Record_>>;
    getTotalDonations(): Promise<bigint>;
    getTotalSpending(): Promise<bigint>;
    getTrustBalance(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    heartbeatLiveViewer(sessionId: string): Promise<void>;
    incrementSiteViews(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    registerLiveViewer(sessionId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unregisterLiveViewer(sessionId: string): Promise<void>;
    updateDonorProfileAdmin(donorId: string, displayName: string, email: string | null, phone: string): Promise<void>;
    updateSpendingRecord(id: string, amount: bigint, description: string): Promise<void>;
}
import type { DonationInput as _DonationInput, DonorProfile as _DonorProfile, DonorPublicProfile as _DonorPublicProfile, Record__1 as _Record__1, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDonation(arg0: DonationInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonation(to_candid_DonationInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonation(to_candid_DonationInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSpendingRecord(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSpendingRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSpendingRecord(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmAllPendingDonations(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmAllPendingDonations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmAllPendingDonations();
            return result;
        }
    }
    async confirmDonation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmDonation(arg0);
            return result;
        }
    }
    async declineDonation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineDonation(arg0);
            return result;
        }
    }
    async deleteSpendingRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSpendingRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSpendingRecord(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonations(arg0: bigint, arg1: bigint): Promise<Array<Record__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonations(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonations(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorDonations(arg0: string): Promise<Array<Record__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorDonations(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorDonations(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorProfile(arg0: string): Promise<DonorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorProfiles(): Promise<Array<DonorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorProfiles();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorProfiles();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorPublicProfile(arg0: string): Promise<DonorPublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorPublicProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorPublicProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorPublicProfiles(): Promise<Array<DonorPublicProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorPublicProfiles();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorPublicProfiles();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteMetrics(): Promise<Metrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteMetrics();
            return result;
        }
    }
    async getSpendingRecords(arg0: bigint, arg1: bigint): Promise<Array<Record_>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingRecords(arg0, arg1);
            return result;
        }
    }
    async getTotalDonations(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalDonations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalDonations();
            return result;
        }
    }
    async getTotalSpending(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSpending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSpending();
            return result;
        }
    }
    async getTrustBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrustBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrustBalance();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async heartbeatLiveViewer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.heartbeatLiveViewer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.heartbeatLiveViewer(arg0);
            return result;
        }
    }
    async incrementSiteViews(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementSiteViews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementSiteViews();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerLiveViewer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerLiveViewer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerLiveViewer(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unregisterLiveViewer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unregisterLiveViewer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unregisterLiveViewer(arg0);
            return result;
        }
    }
    async updateDonorProfileAdmin(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonorProfileAdmin(arg0, arg1, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonorProfileAdmin(arg0, arg1, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateSpendingRecord(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSpendingRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSpendingRecord(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_DonorProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorProfile): DonorProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DonorPublicProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorPublicProfile): DonorPublicProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Record__1_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record__1): Record__1 {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DonorProfile]): DonorProfile | null {
    return value.length === 0 ? null : from_candid_DonorProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DonorPublicProfile]): DonorPublicProfile | null {
    return value.length === 0 ? null : from_candid_DonorPublicProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    utr: string;
    status: _Status;
    donorId: string;
    description: string;
    timestamp: _Time;
    amount: bigint;
}): {
    id: string;
    utr: string;
    status: Status;
    donorId: string;
    description: string;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        utr: value.utr,
        status: from_candid_Status_n14(_uploadFile, _downloadFile, value.status),
        donorId: value.donorId,
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    principal: [] | [Principal];
    displayName: string;
    joinedTimestamp: _Time;
    email: [] | [string];
    phone: string;
    totalDonated: bigint;
}): {
    id: string;
    principal?: Principal;
    displayName: string;
    joinedTimestamp: Time;
    email?: string;
    phone: string;
    totalDonated: bigint;
} {
    return {
        id: value.id,
        principal: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.principal)),
        displayName: value.displayName,
        joinedTimestamp: value.joinedTimestamp,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        phone: value.phone,
        totalDonated: value.totalDonated
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    principal: [] | [Principal];
    maskedPhone: string;
    displayName: string;
    joinedTimestamp: _Time;
    email: [] | [string];
    totalDonated: bigint;
}): {
    id: string;
    principal?: Principal;
    maskedPhone: string;
    displayName: string;
    joinedTimestamp: Time;
    email?: string;
    totalDonated: bigint;
} {
    return {
        id: value.id,
        principal: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.principal)),
        maskedPhone: value.maskedPhone,
        displayName: value.displayName,
        joinedTimestamp: value.joinedTimestamp,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        totalDonated: value.totalDonated
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
} | {
    failed: null;
}): Status {
    return "pending" in value ? Status.pending : "confirmed" in value ? Status.confirmed : "failed" in value ? Status.failed : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record__1>): Array<Record__1> {
    return value.map((x)=>from_candid_Record__1_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorProfile>): Array<DonorProfile> {
    return value.map((x)=>from_candid_DonorProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorPublicProfile>): Array<DonorPublicProfile> {
    return value.map((x)=>from_candid_DonorPublicProfile_n22(_uploadFile, _downloadFile, x));
}
function to_candid_DonationInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationInput): _DonationInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    utr: string;
    displayName: string;
    donorId: string;
    description: string;
    email?: string;
    phone: string;
    amount: bigint;
}): {
    utr: string;
    displayName: string;
    donorId: string;
    description: string;
    email: [] | [string];
    phone: string;
    amount: bigint;
} {
    return {
        utr: value.utr,
        displayName: value.displayName,
        donorId: value.donorId,
        description: value.description,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone,
        amount: value.amount
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
